### ISSUE TITLE
希望完善部署教程

### ISSUE THREAD

**Issue by caixiaohaier** [sky22333/hubproxy#15]
如标题所示，本人略新手，只看到一键拉取docker并运行命令，从该命令只知晓使用了5000端口，并未获取其他消息，从上下文知晓主配置文件在/opt/hubproxy/config.toml，但从官方给的一键拉取docker命令又没看到挂载该目录，以及不知道如何配置自己的域名，以及映射443、80等WEB端口。我使用一键拉取docker并运行命令后，使用nginx反代该程序5000端口却无法访问，不知晓具体如何使用该程序，若能稍微完善下教程，感激不敬。

**Comment by sky22333** [comment]
域名反代一下即可。没有映射配置文件是因为方便小白快速部署，容器内的配置文件映射可以[查看这里](https://github.com/sky22333/hubproxy/blob/main/docker-compose.yml)，ngxin我用的少，具体配置可以问AI，只需正常反代`127.0.0.1:5000`即可。后续我优化一下详细部署教程。

**Comment by wxyShine** [comment]
写个compose.yml  
```yml
services:
    hubproxy:
        container_name: hubproxy
        ports:
            - 5000:5000
        restart: always
        image: ghcr.io/sky22333/hubproxy
```

docker compose up -d  启动
